services:
  docker-registry:
    image: registry:2.8.3
    container_name: docker-registry
    restart: unless-stopped
    volumes:
      - ./docker-registry/config.yml:/etc/docker/registry/config.yml
      - ./docker-registry/registry:/var/lib/registry
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://localhost:5000/v2/ || exit 1",
        ]
      start_period: 10s
      start_interval: 1s
      interval: 5m
      timeout: 10s
      retries: 3

  docker-registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: docker-registry-ui
    restart: unless-stopped
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://docker-registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    depends_on:
      docker-registry:
        condition: service_healthy

  docker-registry-garbagecollector:
    image: docker-registry-garbagecollector:latest
    container_name: docker-registry-garbagecollector
    restart: unless-stopped
    volumes:
      - ./docker-registry/registry:/var/lib/registry
      - //var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINER_NAME=docker-registry
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      docker-registry:
        condition: service_healthy
      docker-registry-ui:
        condition: service_started
